apiVersion: v1
baseDomain: example.com 
credentialsMode: Mint 
controlPlane:   
  hyperthreading: Enabled 
  name: master
  platform:
    aws:
      zones:
      - us-isob-east-1a
      - us-isob-east-1b
      - us-isob-east-1c
      type: m5.2xlarge
      # additionalSecurityGroupIDs:
      #   - sg-1 
      #   - sg-2
      # rootVolume:
      #   iops: 4000
      #   size: 500
      #   type: io1 
      # metadataService:
      #   authentication: Optional 
  replicas: 3
compute: 
- hyperthreading: Enabled 
  name: worker
  platform:
    aws:
      zones:
      - us-isob-east-1a
      - us-isob-east-1b
      - us-isob-east-1c
      type: r5.2xlarge
      # additionalSecurityGroupIDs:
      #   - sg-3 
      #   - sg-4
      # rootVolume:
      #   iops: 2000
      #   size: 500
      #   type: io1 
      # metadataService:
      #   authentication: Optional 
  replicas: 3
metadata:
  name: test-cluster 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.10.10.0/23
  networkType: OVNKubernetes 
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-isob-east-1 
    amiID: ami-96c6f8f7   
    subnets: 
    - subnet-1
    - subnet-2
    - subnet-3
    serviceEndpoints: 
      - name: tagging
        url: https://tagging.us-isob-east-1.amazonaws.com
      - name: iam
        url: https://iam.us-isob-east-1.amazonaws.com
      - name: route53
        url: https://route53resolver.us-isob-east-1.amazonaws.com
      - name: ec2
        url: https://ec2.us-isob-east-1.amazonaws.com
      - name: s3
        url: https://s3.us-isob-east-1.amazonaws.com
      - name: elasticloadbalancing
        url: https://elasticloadbalancing.us-isob-east-1.amazonaws.com
    # hostedZone: Z3URY6TWQ91KVV 
    # propagateUserTags: true 
    # userTags:
    #   adminContact: jdoe
    #   costCenter: 7536
fips: true 
sshKey: ssh-ed25519 AAAA... 
publish: Internal 
pullSecret: '{"auths": ...}' 
additionalTrustBundle: | 
    -----BEGIN CERTIFICATE-----
    <MY_TRUSTED_CA_CERT>
    -----END CERTIFICATE-----
