apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
archiveSize: 2
storageConfig:
  local:
    path: ./metadata/platform/openshift
mirror:
  platform:
    graph: true
    channels:
      - name: stable-4.16
        type: ocp
        shortestPath: true
        minVersion: 4.15.34
        # maxVersion: 4.16.14
